spring.application.name=user-service
server.port=8081 

# Postgresql Config
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=taskflow_user
spring.datasource.password=taskflow_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=user_service

jwt.secret=taskflow-secret-key-change-in-production-min-256-bits-long
jwt.expiration=86400000